#!/usr/bin/env tsx
/**
 * Helper script to export MyFitnessPal session cookies from your browser.
 *
 * @remarks
 * This script provides instructions for manually exporting cookies since
 * automatic browser cookie extraction requires native dependencies.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as readline from 'readline';

const INSTRUCTIONS = `
================================================================================
                   MyFitnessPal Cookie Export Helper
================================================================================

To use this MCP server, you need to export your MyFitnessPal session cookie.

STEP 1: Log into MyFitnessPal
-----------------------------
1. Open your browser (Chrome, Firefox, Safari, or Edge)
2. Go to https://www.myfitnesspal.com
3. Log in to your account

STEP 2: Export the Session Cookie
----------------------------------
1. Open your browser's Developer Tools (F12 or Cmd+Option+I on Mac)
2. Go to the "Application" tab (Chrome) or "Storage" tab (Firefox)
3. In the left sidebar, expand "Cookies" and click on "www.myfitnesspal.com"
4. Look for a cookie named one of these:
   - "mfp_session"
   - "_session_id" 
   - Or any cookie that looks like a session token
5. Copy the entire "Value" of that cookie

STEP 3: Save to .env file
--------------------------
Create a .env file in the project root with this content:

    MFP_SESSION_COOKIE=<paste your cookie value here>
    MFP_USERNAME=<your myfitnesspal username>

The MFP_USERNAME is optional but helps with verification.

================================================================================
`;

/**
 * Creates a readline interface for user input.
 */
function createReadline(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

/**
 * Prompts the user for input.
 */
async function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

/**
 * Main function to guide the user through cookie export.
 */
async function main(): Promise<void> {
  console.log(INSTRUCTIONS);

  const rl = createReadline();

  try {
    const shouldContinue = await prompt(
      rl,
      'Would you like me to help you create the .env file? (y/n): '
    );

    if (shouldContinue.toLowerCase() !== 'y') {
      console.log('\nNo problem! Follow the instructions above to manually create your .env file.');
      rl.close();
      return;
    }

    console.log('\nGreat! Please paste your session cookie value below.');
    console.log('(The cookie value is usually a long string of letters and numbers)\n');

    const cookieValue = await prompt(rl, 'Session Cookie Value: ');

    if (!cookieValue) {
      console.log('\nNo cookie value provided. Please try again.');
      rl.close();
      return;
    }

    const username = await prompt(rl, 'MyFitnessPal Username (optional, press Enter to skip): ');

    // Create the .env content
    let envContent = `# MyFitnessPal MCP Configuration
# Generated by export-cookies script

# Session cookie from your browser
MFP_SESSION_COOKIE=${cookieValue}
`;

    if (username) {
      envContent += `
# Your MyFitnessPal username
MFP_USERNAME=${username}
`;
    }

    // Write to .env file
    const envPath = path.join(process.cwd(), '.env');
    
    if (fs.existsSync(envPath)) {
      const overwrite = await prompt(
        rl,
        '\n.env file already exists. Overwrite? (y/n): '
      );
      
      if (overwrite.toLowerCase() !== 'y') {
        console.log('\nAborted. Your existing .env file was not modified.');
        console.log('You can manually add the following to your .env file:\n');
        console.log(envContent);
        rl.close();
        return;
      }
    }

    fs.writeFileSync(envPath, envContent, 'utf-8');
    console.log('\n✓ Successfully created .env file!');
    console.log(`  Location: ${envPath}`);
    console.log('\nYou can now start the MCP server with: npm run dev');
    console.log('\nNote: Session cookies expire after about 30 days.');
    console.log('If you get authentication errors, run this script again to update your cookie.');

  } finally {
    rl.close();
  }
}

main().catch((error) => {
  console.error('Error:', error);
  process.exit(1);
});



